name: Build & Deploy

on:
  push:
    branches:
      - main
      - worldcoin
      - celo

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: benbarahona/wolf-of-web3

jobs:
  build_backend:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker Buildx Install
        uses: docker/setup-buildx-action@v3

      - name: Build and Push Backend Image
        uses: docker/build-push-action@v5
        with:
          context: ./backend/
          file: ./backend/Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:production
          cache-from: type=gha
          cache-to: type=gha,mode=max

  build_frontend_celo:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Enable Corepack & Set Yarn version
        run: |
          corepack enable
          corepack prepare yarn@3.2.3 --activate

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker Buildx Install
        uses: docker/setup-buildx-action@v3

      - name: Build and Push Frontend Celo Image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend/
          file: ./frontend/Dockerfile.celo
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:celo
          cache-from: type=gha
          cache-to: type=gha,mode=max

  build_frontend_worldcoin:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Enable Corepack & Set Yarn version
        run: |
          corepack enable
          corepack prepare yarn@3.2.3 --activate

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker Buildx Install
        uses: docker/setup-buildx-action@v3

      - name: Build and Push Frontend Worldcoin Image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend/
          file: ./frontend/Dockerfile.worldcoin
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:worldcoin
          cache-from: type=gha
          cache-to: type=gha,mode=max
